openapi: 3.0.3
info:
  title: alex-api
  description: HTTP server in Go with Swagger endpoints definition. An API for all my hobbies.
  contact:
    name: API Support
    email: alexnou@gmail.com
  version: 0.5.3
servers:
- url: https://alex-api.herokuapp.com
tags:
- name: Dyson Sphere Program
  description: Endpoints related to Dyson Sphere Program
- name: Black Desert Online
  description: Endpoints related to Black Desert Online
- name: Twitter
  description: Endpoints related to using twitter's API
- name: Analytics
  description: Keeping track of things
paths:
  /dsp/computedRecipes:
    post:
      tags:
      - Dyson Sphere Program
      summary: Get the computed recipe
      description: Get the computed recipe
      operationId: getDSPComputedRecipe
      parameters:
      - in: query
        name: group
        schema:
          type: boolean
        description: Whether or not to group the recipes in the computed recipe up by name
      - in: query
        name: assemblerLevel
        schema:
          type: number
          example: 2
          default: 2
          enum: [1, 2, 3]
      requestBody:
        $ref: "#/components/requestBodies/ComputedRecipesRequestBody"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ComputedRecipe"
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: recipeRequest
  /dsp/recipes:
    get:
      tags:
      - Dyson Sphere Program
      summary: Get all DSP recipes
      description: Get all DSP recipes
      operationId: getDSPRecipes
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    $ref: "#/components/schemas/Recipe"
  /dsp/recipes/reload:
    post:
      tags:
      - Dyson Sphere Program
      summary: Re-scrapes the DSP recipes
      description: Re-scrapes the DSP recipes
      operationId: reloadDSPRecipes
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                enum:
                - OK
  /twitter/inArt:
    get:
      tags:
      - Twitter
      summary: Get inART
      description: Get inART
      operationId: getInArt
      parameters:
      - name: page
        in: query
        description: Numeric ID of the page to get
        required: true
        schema:
          type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TwitterMedia"
  /bdo/computedRecipes:
    post:
      tags:
      - Black Desert Online
      summary: Get the computed recipe
      description: Get the computed recipe
      operationId: getBDOComputedRecipe
      parameters:
      - in: query
        name: group
        schema:
          type: boolean
        description: Whether or not to group the recipes in the computed recipe up by name
      requestBody:
        $ref: "#/components/requestBodies/ComputedRecipesRequestBody"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ComputedRecipe"
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: recipeRequest
  /bdo/recipes:
    get:
      tags:
      - Black Desert Online
      summary: Get all BDO recipes
      description: Get all BDO recipes
      operationId: getBDORecipes
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    $ref: "#/components/schemas/Recipe"
  /pageview:
    put:
      tags:
      - Analytics
      summary: Track Page View
      description: Track a page view using referrer url. The path in the request body will override the referrer path.
      operationId: pageViewed
      requestBody:
        description:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PageView"
        required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageView"
components:
  requestBodies:
    ComputedRecipesRequestBody:
      description: A JSON object containing your recipe requirements
      required: false
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              required:
              - name
              - rate
              properties:
                name:
                  type: string
                rate:
                  type: number
                requirements:
                  type: object
                  additionalProperties:
                    description: Which recipe to use
                    type: number
              example:
                name: "Proliferator Mk.III"
                rate: 2.0
                requirements:
                  "Carbon Nanotube": 1
  schemas:
    TwitterMedia:
      required:
      - author
      - createdAt
      - height
      - possiblySensitive
      - tweetId
      - url
      - width
      type: object
      properties:
        author:
          $ref: "#/components/schemas/TwitterAuthor"
        tweetId:
          type: string
        url:
          type: string
        width:
          type: integer
        height:
          type: integer
        possiblySensitive:
          type: boolean
        createdAt:
          type: string
        updated:
          type: string
    TwitterAuthor:
      required:
      - id
      - name
      - username
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        username:
          type: string
    Recipe:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        action:
          type: string
        facility:
          type: string
        image:
          type: string
        ingredients:
          $ref: "#/components/schemas/Ingredients"
        quantityProduced:
          type: number
        minProduced:
          type: number
        maxProduced:
          type: number
        timeToProduce:
          type: number
        marketData:
          $ref: "#/components/schemas/MarketData"
    Ingredients:
      type: object
      additionalProperties:
        type: string
      example:
        Plank: 1
    ComputedRecipe:
      required:
      - name
      type: object
      properties:
        name:
          type: string
        facility:
          type: string
        numFacilitiesNeeded:
          type: number
        itemsConsumedPerSec:
          type: object
          properties: {}
        secondsSpentPerCraft:
          type: number
        craftingPerSec:
          type: number
        usedFor:
          type: string
        depth:
          type: number
        image:
          type: string
    MarketData:
      type: object
      properties:
        marketDataID:
          type: string
        lastUpdateAttempt:
          type: number
        lastUpdated:
          type: number
        price:
          type: number
        quantity:
          type: number
        totalTradeCount:
          type: number
        name:
          type: string
    PageView:
      type: object
      properties:
        domain:
          type: string
        path:
          type: string
        timesTracked:
          type: number
        lastTracked:
          type: number