version: "3"

tasks:
    dev:
        desc: Run and autoreload the app
        cmds:
        - nodemon --exec 'go run main.go' --watch './**/*.go' --signal SIGTERM

    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin main.go

    run:
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go

    swagger.gen:
        desc: Generate Go code
        cmds:
        - swagger generate server swagger.json -A addi

    swagger.validate:
        desc: Validate swagger
        cmds:
        - swagger validate swagger.json

    swagger.doc:
        desc: Doc for swagger
        cmds:
        - swagger serve --no-open --port=80 ./swagger.json