// Code generated by MockGen. DO NOT EDIT.
// Source: db.go

// Package server is a generated GoMock package.
package server

import (
	data "alex-api/internal/data"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// GetRecipes mocks base method.
func (m *MockDB) GetRecipes(skip, limit *int64) ([]data.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipes", skip, limit)
	ret0, _ := ret[0].([]data.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipes indicates an expected call of GetRecipes.
func (mr *MockDBMockRecorder) GetRecipes(skip, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipes", reflect.TypeOf((*MockDB)(nil).GetRecipes), skip, limit)
}

// GetTwitterMedia mocks base method.
func (m *MockDB) GetTwitterMedia(skip, limit *int64) ([]data.TwitterMedia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTwitterMedia", skip, limit)
	ret0, _ := ret[0].([]data.TwitterMedia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTwitterMedia indicates an expected call of GetTwitterMedia.
func (mr *MockDBMockRecorder) GetTwitterMedia(skip, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTwitterMedia", reflect.TypeOf((*MockDB)(nil).GetTwitterMedia), skip, limit)
}
