// Code generated by MockGen. DO NOT EDIT.
// Source: db.go

// Package server is a generated GoMock package.
package server

import (
	data "alex-api/internal/data"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// CreatePageView mocks base method.
func (m *MockDB) CreatePageView(pageView data.PageView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePageView", pageView)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePageView indicates an expected call of CreatePageView.
func (mr *MockDBMockRecorder) CreatePageView(pageView interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePageView", reflect.TypeOf((*MockDB)(nil).CreatePageView), pageView)
}

// GetBDORecipes mocks base method.
func (m *MockDB) GetBDORecipes(skip, limit *int64) ([]data.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBDORecipes", skip, limit)
	ret0, _ := ret[0].([]data.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBDORecipes indicates an expected call of GetBDORecipes.
func (mr *MockDBMockRecorder) GetBDORecipes(skip, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBDORecipes", reflect.TypeOf((*MockDB)(nil).GetBDORecipes), skip, limit)
}

// GetDSPRecipes mocks base method.
func (m *MockDB) GetDSPRecipes(skip, limit *int64) ([]data.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDSPRecipes", skip, limit)
	ret0, _ := ret[0].([]data.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDSPRecipes indicates an expected call of GetDSPRecipes.
func (mr *MockDBMockRecorder) GetDSPRecipes(skip, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDSPRecipes", reflect.TypeOf((*MockDB)(nil).GetDSPRecipes), skip, limit)
}

// GetPageView mocks base method.
func (m *MockDB) GetPageView(domain, path string) (data.PageView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageView", domain, path)
	ret0, _ := ret[0].(data.PageView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageView indicates an expected call of GetPageView.
func (mr *MockDBMockRecorder) GetPageView(domain, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageView", reflect.TypeOf((*MockDB)(nil).GetPageView), domain, path)
}

// GetTwitterMedia mocks base method.
func (m *MockDB) GetTwitterMedia(skip, limit *int64) ([]data.TwitterMedia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTwitterMedia", skip, limit)
	ret0, _ := ret[0].([]data.TwitterMedia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTwitterMedia indicates an expected call of GetTwitterMedia.
func (mr *MockDBMockRecorder) GetTwitterMedia(skip, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTwitterMedia", reflect.TypeOf((*MockDB)(nil).GetTwitterMedia), skip, limit)
}

// UpdatePageView mocks base method.
func (m *MockDB) UpdatePageView(pageView data.PageView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePageView", pageView)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePageView indicates an expected call of UpdatePageView.
func (mr *MockDBMockRecorder) UpdatePageView(pageView interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePageView", reflect.TypeOf((*MockDB)(nil).UpdatePageView), pageView)
}
