// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"addi/models"
)

// GetDspOKCode is the HTTP code returned for type GetDspOK
const GetDspOKCode int = 200

/*GetDspOK OK

swagger:response getDspOK
*/
type GetDspOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Recipe `json:"body,omitempty"`
}

// NewGetDspOK creates GetDspOK with default headers values
func NewGetDspOK() *GetDspOK {

	return &GetDspOK{}
}

// WithPayload adds the payload to the get dsp o k response
func (o *GetDspOK) WithPayload(payload []*models.Recipe) *GetDspOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dsp o k response
func (o *GetDspOK) SetPayload(payload []*models.Recipe) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDspOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Recipe, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
