// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDSPRecipesHandlerFunc turns a function with the right signature into a get d s p recipes handler
type GetDSPRecipesHandlerFunc func(GetDSPRecipesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDSPRecipesHandlerFunc) Handle(params GetDSPRecipesParams) middleware.Responder {
	return fn(params)
}

// GetDSPRecipesHandler interface for that can handle valid get d s p recipes params
type GetDSPRecipesHandler interface {
	Handle(GetDSPRecipesParams) middleware.Responder
}

// NewGetDSPRecipes creates a new http.Handler for the get d s p recipes operation
func NewGetDSPRecipes(ctx *middleware.Context, handler GetDSPRecipesHandler) *GetDSPRecipes {
	return &GetDSPRecipes{Context: ctx, Handler: handler}
}

/* GetDSPRecipes swagger:route GET /dsp/recipes getDSPRecipes

Get all DSP recipes

Get all DSP recipes

*/
type GetDSPRecipes struct {
	Context *middleware.Context
	Handler GetDSPRecipesHandler
}

func (o *GetDSPRecipes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDSPRecipesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
