// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"addi/models"
)

// GetDspItemsOKCode is the HTTP code returned for type GetDspItemsOK
const GetDspItemsOKCode int = 200

/*GetDspItemsOK OK

swagger:response getDspItemsOK
*/
type GetDspItemsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.DSPItem `json:"body,omitempty"`
}

// NewGetDspItemsOK creates GetDspItemsOK with default headers values
func NewGetDspItemsOK() *GetDspItemsOK {

	return &GetDspItemsOK{}
}

// WithPayload adds the payload to the get dsp items o k response
func (o *GetDspItemsOK) WithPayload(payload []*models.DSPItem) *GetDspItemsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dsp items o k response
func (o *GetDspItemsOK) SetPayload(payload []*models.DSPItem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDspItemsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.DSPItem, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
