// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDSPRecipeHandlerFunc turns a function with the right signature into a get d s p recipe handler
type GetDSPRecipeHandlerFunc func(GetDSPRecipeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDSPRecipeHandlerFunc) Handle(params GetDSPRecipeParams) middleware.Responder {
	return fn(params)
}

// GetDSPRecipeHandler interface for that can handle valid get d s p recipe params
type GetDSPRecipeHandler interface {
	Handle(GetDSPRecipeParams) middleware.Responder
}

// NewGetDSPRecipe creates a new http.Handler for the get d s p recipe operation
func NewGetDSPRecipe(ctx *middleware.Context, handler GetDSPRecipeHandler) *GetDSPRecipe {
	return &GetDSPRecipe{Context: ctx, Handler: handler}
}

/* GetDSPRecipe swagger:route POST /dsp getDSPRecipe

Get the optimal recipe

Get the optimal recipe

*/
type GetDSPRecipe struct {
	Context *middleware.Context
	Handler GetDSPRecipeHandler
}

func (o *GetDSPRecipe) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDSPRecipeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
