// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostDspItemsReloadHandlerFunc turns a function with the right signature into a post dsp items reload handler
type PostDspItemsReloadHandlerFunc func(PostDspItemsReloadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDspItemsReloadHandlerFunc) Handle(params PostDspItemsReloadParams) middleware.Responder {
	return fn(params)
}

// PostDspItemsReloadHandler interface for that can handle valid post dsp items reload params
type PostDspItemsReloadHandler interface {
	Handle(PostDspItemsReloadParams) middleware.Responder
}

// NewPostDspItemsReload creates a new http.Handler for the post dsp items reload operation
func NewPostDspItemsReload(ctx *middleware.Context, handler PostDspItemsReloadHandler) *PostDspItemsReload {
	return &PostDspItemsReload{Context: ctx, Handler: handler}
}

/* PostDspItemsReload swagger:route POST /dsp/items/reload postDspItemsReload

Re-scrapes the DSP items

Re-scrapes the DSP items

*/
type PostDspItemsReload struct {
	Context *middleware.Context
	Handler PostDspItemsReloadHandler
}

func (o *PostDspItemsReload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostDspItemsReloadParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
