// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"addi/models"
)

// PostDspOKCode is the HTTP code returned for type PostDspOK
const PostDspOKCode int = 200

/*PostDspOK OK

swagger:response postDspOK
*/
type PostDspOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Recipe `json:"body,omitempty"`
}

// NewPostDspOK creates PostDspOK with default headers values
func NewPostDspOK() *PostDspOK {

	return &PostDspOK{}
}

// WithPayload adds the payload to the post dsp o k response
func (o *PostDspOK) WithPayload(payload []*models.Recipe) *PostDspOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post dsp o k response
func (o *PostDspOK) SetPayload(payload []*models.Recipe) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDspOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Recipe, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
