// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostDspItemsReloadOKCode is the HTTP code returned for type PostDspItemsReloadOK
const PostDspItemsReloadOKCode int = 200

/*PostDspItemsReloadOK OK

swagger:response postDspItemsReloadOK
*/
type PostDspItemsReloadOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostDspItemsReloadOK creates PostDspItemsReloadOK with default headers values
func NewPostDspItemsReloadOK() *PostDspItemsReloadOK {

	return &PostDspItemsReloadOK{}
}

// WithPayload adds the payload to the post dsp items reload o k response
func (o *PostDspItemsReloadOK) WithPayload(payload string) *PostDspItemsReloadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post dsp items reload o k response
func (o *PostDspItemsReloadOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDspItemsReloadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
