// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ReloadDSPRecipesOKCode is the HTTP code returned for type ReloadDSPRecipesOK
const ReloadDSPRecipesOKCode int = 200

/*ReloadDSPRecipesOK OK

swagger:response reloadDSPRecipesOK
*/
type ReloadDSPRecipesOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewReloadDSPRecipesOK creates ReloadDSPRecipesOK with default headers values
func NewReloadDSPRecipesOK() *ReloadDSPRecipesOK {

	return &ReloadDSPRecipesOK{}
}

// WithPayload adds the payload to the reload d s p recipes o k response
func (o *ReloadDSPRecipesOK) WithPayload(payload string) *ReloadDSPRecipesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reload d s p recipes o k response
func (o *ReloadDSPRecipesOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReloadDSPRecipesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
