// Code generated by go-swagger; DO NOT EDIT.

// Package restapi go-rest-api
//
//  HTTP server in Go with Swagger endpoints definition.
//  Schemes:
//    http
//    https
//  Host: protected-sea-18092.herokuapp.com
//  BasePath: /
//  Version: 0.1.0
//  Contact: API Support<alexnou@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
