name: Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: go-semantic-release
        uses: go-semantic-release/action@v1.17.0
        with:
          github-token: ${{ secrets.TOKEN }}
  generate_client:
    runs-on: ubuntu-latest
    needs: [build-test-release]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check spec
        id: spec_changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            ./openapi.yaml
      - name: Repository Dispatch
        if: steps.spec_changed.outputs.any_changed == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: NekoFluff/alex-api-typescript-client
          event-type: generate
          client-payload: '{"release": "${{ needs.prerelease.outputs.release_id }}"}'
