// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DSPItem d s p item
//
// swagger:model DSPItem
type DSPItem struct {

	// made in
	MadeIn string `json:"madeIn,omitempty"`

	// materials
	Materials []*DSPMaterial `json:"materials"`

	// name
	Name string `json:"name,omitempty"`

	// produce
	Produce float64 `json:"produce,omitempty"`

	// time
	Time float64 `json:"time,omitempty"`
}

// Validate validates this d s p item
func (m *DSPItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMaterials(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DSPItem) validateMaterials(formats strfmt.Registry) error {
	if swag.IsZero(m.Materials) { // not required
		return nil
	}

	for i := 0; i < len(m.Materials); i++ {
		if swag.IsZero(m.Materials[i]) { // not required
			continue
		}

		if m.Materials[i] != nil {
			if err := m.Materials[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("materials" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("materials" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this d s p item based on the context it is used
func (m *DSPItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMaterials(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DSPItem) contextValidateMaterials(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Materials); i++ {

		if m.Materials[i] != nil {
			if err := m.Materials[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("materials" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("materials" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DSPItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DSPItem) UnmarshalBinary(b []byte) error {
	var res DSPItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
