// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Recipe recipe
//
// swagger:model Recipe
type Recipe struct {

	// consumes per sec
	ConsumesPerSec interface{} `json:"consumesPerSec,omitempty"`

	// crafting per second
	CraftingPerSecond float64 `json:"craftingPerSecond,omitempty"`

	// for
	For string `json:"for,omitempty"`

	// made in
	MadeIn string `json:"madeIn,omitempty"`

	// number of facilities needed
	NumberOfFacilitiesNeeded float64 `json:"numberOfFacilitiesNeeded,omitempty"`

	// produce
	Produce string `json:"produce,omitempty"`

	// seconds spend per crafting
	SecondsSpendPerCrafting float64 `json:"secondsSpendPerCrafting,omitempty"`
}

// Validate validates this recipe
func (m *Recipe) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this recipe based on context it is used
func (m *Recipe) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Recipe) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Recipe) UnmarshalBinary(b []byte) error {
	var res Recipe
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
